pull_request_rules:
  - name: Ready to grading test
    conditions:
      - base=master
      - -title~=(?i)wip
      - label!=work-in-progress
      - -draft
      - -conflict
    actions:
      merge:
          method: merge

